server:
  port: 8013
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          search-paths: repository
          uri: git@github.com:lishunyi123/spring-config-repository.git
          username: lishunyi123
          password: RailEdefjolidC2
eureka:
  registerName: lishunyi
  registerPassword: 123456
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.registerName}:${eureka.registerPassword}@${eureka.instance.hostname}:8001/eureka